---
version: 2
jobs:
  build-and-test:
    machine: true

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Generate a unique tunnel id
          command: echo $(uuidgen) > ~/sauce_tunnel_id

      - run: |
          wget https://saucelabs.com/downloads/sc-4.5.1-linux.tar.gz
          tar -xzf sc-4.5.1-linux.tar.gz

      - run:
          name: Create the Sauce Connect tunnel
          command: cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --tunnel-identifier $(cat ~/sauce_tunnel_id) --readyfile ~/sauce_is_ready
          background: true

      - run:
          name: Wait for the tunnel to be ready
          command: while [ ! -e ~/sauce_is_ready ]; do sleep 1; done

      - run:
          name: Create a OCE container
          command: |
            cd ~
            git clone https://github.com/opennms-forge/docker-sentinel.git
            cd docker-sentinel/
            git checkout -b release-oce origin/release-oce
            docker build -t opennms/sentinel:oce .

      - run:
          name: Run the tests
          # TODO: Update this to capture the results of the JUnit test runs
          command: |
            export SAUCE_TUNNEL_ID=$(cat ~/sauce_tunnel_id)
            mvn integration-test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - run:
          name: Wait for Sauce Connect to close the tunnel
          command: killall --wait sc
          when: always

workflows:
  version: 2
  # Runs on every commit without triggers
  commit:
    jobs:
    - build-and-test
  # Runs on a scheduled trigger nightly
  nightly:
    triggers:
    - schedule:
        # Run daily @ 5:00am UTC
        #cron: "0 5 * * *"
        # TODO: Revert to daily on master
        # Run hourly
        cron: "0 * * * *"
        filters:
          branches:
            only:
            # TODO: This should be changed to master branch
            - mbrooks/oce-2
    jobs:
    - build-and-test
# Temporary to get the test to run every half hour
# TODO: Remove this
  temp:
    triggers:
    - schedule:
        cron: "30 * * * *"
        filters:
          branches:
            only:
            - mbrooks/oce-2            
    jobs:
    - build-and-test
