version: 2
jobs:
  build:
    machine: true

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Generate a unique tunnel id
          command: echo $(uuidgen) > ~/sauce_tunnel_id

      - run: |
          wget https://saucelabs.com/downloads/sc-latest-linux.tar.gz
          tar -xzf sc-latest-linux.tar.gz

      - run:
          name: Create the Sauce Connect tunnel
          command: cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --tunnel-identifier $(cat ~/sauce_tunnel_id) --readyfile ~/sauce_is_ready
          background: true

      - run:
          name: Wait for the tunnel to be ready
          command: while [ ! -e ~/sauce_is_ready ]; do sleep 1; done

      - run:
          name: Run the tess
          command: |
            export SAUCE_TUNNEL_ID=$(cat ~/sauce_tunnel_id)
            mvn integration-test

      - run:
          name: Wait for Sauce Connect to close the tunnel
          command: killall --wait sc
          when: always

